sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: '5.4'
      env: SYMFONY_VERSION='2.3.*'
    - php: '7.0'
      env: SYMFONY_VERSION='2.7.*'
    - php: '7.0'
      env: SYMFONY_VERSION='2.8.*'
    - php: '7.0'
      env: SYMFONY_VERSION='3.0.*'
  allow_failures:
    - php: nightly

install:
  - if [ "hhvm" != "$TRAVIS_PHP_VERSION" ]; then
        phpenv config-rm xdebug.ini;
    fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then
        composer require --no-update "symfony/symfony:${SYMFONY_VERSION}";
    fi;
  - composer install --prefer-dist

script: vendor/bin/phpunit
