sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - nightly

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: COVERAGE='true'
    - php: '7.0'
      env: SYMFONY_VERSION='2.3.*'
    - php: '7.0'
      env: SYMFONY_VERSION='2.7.*'
    - php: '7.0'
      env: SYMFONY_VERSION='2.8.*'
    - php: '7.0'
      env: SYMFONY_VERSION='3.0.*'
  allow_failures:
    - php: nightly

install:
  - phpenv config-rm xdebug.ini
  - |
    if [ -n "$SYMFONY_VERSION" ]; then
        composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"
    fi
  - composer install --prefer-dist $COMPOSER_FLAGS

script:
  - |
    if [ -n "$COVERAGE" ]; then
        phpdbg -qrr vendor/bin/phpunit --testdox --verbose
    else
        vendor/bin/phpunit
    fi;
