language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    # Test against LTS releases
    - php: 5.5
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.5
      env: SYMFONY_VERSION='2.7.*'
    # Test against dev dependencies
    - php: 5.6
      env: DEPS=dev
    - php: 5.6
      env: DEPS=dev SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: DEPS=dev SYMFONY_VERSION='3.0.*'

before_install:
  - composer self-update
  - if [ "$DEPS" = 'dev' ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

before_script:
  - composer install --prefer-source

script: vendor/bin/phpunit
