language: php

cache:
  directories:
    - "$HOME/.composer/cache/files"

php:
  - '7.1'
  - '7.2'
  - nightly

env:
  global:
    - PHPUNIT_FLAGS='--stop-on-failure --verbose'

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.2'
      env: COVERAGE='true'
    - php: '7.2'
      env: SYMFONY_VERSION='~3.4.0'
    - php: '7.2'
      env: SYMFONY_VERSION='~4.0.0'
    - php: '7.2'
      env: SYMFONY_VERSION='~4.1.0@dev'
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION='~4.1.0@dev'

before_install:
  - set -eo pipefail
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini || true
  - |
    if [ -n "$SYMFONY_VERSION" ]; then
        PHPUNIT_BIN=vendor-bin/symfony/bin/phpunit
        PHPUNIT_CONFIG=phpunit_symfony.xml.dist
    else
        PHPUNIT_BIN=bin/phpunit
        PHPUNIT_CONFIG=phpunit.xml.dist
    fi
  - |
    if [ -n "$COVERAGE" ]; then
        PHPUNIT_BIN="phpdbg -qrr $PHPUNIT_BIN"
        PHPUNIT_FLAGS="$PHPUNIT_FLAGS --testdox --coverage-text --exclude-group=integration"
    fi
  - |
    if [ "TRAVIS_PHP_VERSION" == "nightly" ]; then
        COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"
    fi

install:
  - composer update --prefer-dist $COMPOSER_FLAGS
  - |
    if [ -n "$SYMFONY_VERSION" ]; then
        composer bin symfony require --no-update symfony/symfony "symfony/symfony:${SYMFONY_VERSION}"
    fi
  - composer bin all update $COMPOSER_FLAGS
  - vendor-bin/covers-validator/bin/covers-validator -c $PHPUNIT_CONFIG

script: $PHPUNIT_BIN -c $PHPUNIT_CONFIG $PHPUNIT_FLAGS

notifications:
    email: false
