sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.0'
  - nightly

env:
  - PHPUNIT_CONFIG='phpunit.xml.dist'
  - PHPUNIT_FLAGS='--stop-on-failure --verbose'

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: COVERAGE='true'
    - php: '7.0'
      env: SYMFONY_VERSION='^3.0'
    - php: '7.0'
      env: SYMFONY_VERSION='^3.1'
    - php: '7.0'
      env: SYMFONY_VERSION='^3.2@dev'
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION='^3.2@dev'

install:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist $COMPOSER_FLAGS
  - |
    if [ -n "$SYMFONY_VERSION" ]; then
        composer bin symfony require symfony/symfony "symfony/symfony:${SYMFONY_VERSION}"
        PHPUNIT_CONFIG='phpunit_symfony.xml.dist'
    fi

script:
  - |
    if [ -n "$COVERAGE" ]; then
        phpdbg -qrr vendor/bin/phpunit -c PHPUNIT_CONFIG PHPUNIT_FLAGS --testdox --coverage-text --exclude-group=integration,symfony
        if [ -n "$SYMFONY_VERSION" ]; then
            phpdbg -qrr vendor/bin/phpunit -c PHPUNIT_CONFIG PHPUNIT_FLAGS --coverage-text --group=integration
        else
            phpdbg -qrr vendor/bin/phpunit -c PHPUNIT_CONFIG PHPUNIT_FLAGS --coverage-text --group=integration,symfony
        fi
    else
        vendor/bin/phpunit -c PHPUNIT_CONFIG --stop-on-failure
    fi;

notifications:
    email: false
