language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '5.6'
  - '7.0'
  - '7.1'

matrix:
  fast_finish: true
  include:
    - php: '5.6'
      env:
        - SYMFONY_VERSION='~2.7.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '5.6'
      env: SYMFONY_VERSION='~2.7.0'
    - php: '7.0'
      env:
        - SYMFONY_VERSION='~2.7.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.1'
      env: SYMFONY_VERSION='~2.7.0'
    - php: '7.1'
      env: SYMFONY_VERSION='~2.8.0'
    - php: '7.1'
      env: SYMFONY_VERSION='~3.1.0'
    - php: '7.1'
      env: SYMFONY_VERSION='~3.2.0'
    - php: '7.1'
      env: SYMFONY_VERSION='~3.3.0@dev'
    - php: 'nightly'
      env:
        - COMPOSER_FLAGS='--ignore-platform-reqs'
        - SYMFONY_DEPRECATIONS_HELPER='weak'
        - SYMFONY_VERSION='~3.3.0@dev'
  allow_failures:
    - php: 'nightly'
    - env: SYMFONY_VERSION='~3.3.0@dev'

install:
  - phpenv config-rm xdebug.ini || true
  - if [ "$SYMFONY_VERSION" != "" ]; then
        composer require --no-update "symfony/symfony:${SYMFONY_VERSION}";
    fi
  - composer update --prefer-dist --no-suggest $COMPOSER_FLAGS

script: vendor/bin/phpunit --verbose

notifications:
  email: false
